FROM node:20-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

WORKDIR /opt/app
COPY . .

RUN chown -R node:node /opt/app

RUN mkdir -p node_modules/.strapi && chown -R node:node node_modules/.strapi

USER node

RUN ["pnpm", "build"]

EXPOSE 1337
CMD ["pnpm", "develop"]