FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt
COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/backend/tsconfig.json ./apps/backend/tsconfig.json


RUN pnpm install --frozen-lockfile


COPY apps/backend /opt/apps/backend


# Now copy the actual source code
# COPY packages/types /opt/packages/types

RUN chown -R node:node /opt/

WORKDIR /opt/apps/backend
USER node

RUN ["pnpm", "build"]

EXPOSE 1337
CMD ["pnpm", "develop"]